### ISSUE TITLE
Problem in running mod06b with raw speech

### ISSUE THREAD

**Issue by pbaljeka** [monikaUPF/modularProsodyTagger#1]
I get the following error on running the mod06b script. 
I have run the mod01, mod02, mod03, mod05b before this as per the README. Am I missing a step?

The following is the command:
praat-ft-annot --run mod06b.praat <basename> <wavefile>
Error: Unknown variable:
« complete
Script line 112 not performed or completed:
« if complete == 0 »
Script “/home/modularProsodyTagger/mod06b.praat” not completed.
Praat: script command <<mod06b.praat /home/modularProsodyTagger/ arctic_a0001>> not completed.

**Comment by monikaUPF** [comment]
You can delete that variable. It is included in the dialog menu if you run the script manually on praat to pick up if you want to visualize all the output of each module or just the predicton, i.e., prosodic phrases and prominence. On the web platform there is an option as well for user to tick on it.
